### ISSUE TITLE
Get User's Geo-based location in a chat with Telegram Bot

### ISSUE THREAD

**Issue by abhi3700** [python-botogram/botogram#138]
I am using this in a callback
```py
import botogram

@bot.command("sendinfo")
def sendinfo_command(chat, message, args):
    """User has to click a button for giving information - Username, Datetime, Location"""
    btns = botogram.Buttons()
    
    btns[0].callback("Username", "username")     # button - Username
    btns[1].callback("Location", "location")     # button - Location
    
    chat.send("Please, select one of the buttons popping below.", attach= btns)

@bot.callback("location")
def location_callback(query, chat, message):
    loc = query.sender.location
    lat = loc.latitude
    lng = loc.longitude
    chat.send(str(lat) + " & " + str(lng))      # test
    query.notify("{latitude} & {longitude} saved.".format(latitude=lat, longitude=lng))

if __name__ == "__main__":
    bot.run()
```
When I am pressing `location` button, then there is no message (i.e. location i.e. lat, lng) sent from Bot in the chat.

![telegram](https://user-images.githubusercontent.com/16472948/63206131-61e88300-c0cc-11e9-94fa-87bea838e022.png)

Can anyone (@MarcoBuster) please help me with this?
I followed the similar technique for callback from my previous [issue](https://github.com/python-botogram/botogram/issues/137)

**Comment by MarcoBuster** [comment]
@abhi3700 You can't get the user's location from a callback query. The user must send its location via the attachments menu.
