### ISSUE TITLE
Bot's reply to a chat message

### ISSUE THREAD

**Issue by abhi3700** [python-botogram/botogram#146]
Hi Guys!,
How to apply this?
```console
User: /setbreed
Bot: please enter breed:-
User: labrador
Bot: 'labrador' saved
```
I mean:
```py
@bot.command("setbreed")
def setbreed_command(chat, message, args):
    chat.send("please enter breed:-")
    // ???
```
Next what??
Anyone please..

**Comment by MarcoBuster** [comment]
This is not a botogram issue, but a software architecture question.
GitHub issues section aren't a forum, please use them only for bug reporting or documented feature requests; use the Telegram group instead.

**Comment by abhi3700** [comment]
I have commented there as well
